name: Run Preprocessing on Trigger

on:
  push:
    paths:
      - 'preprocessing/**'
      - '.github/workflows/preprocessing.yml'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn imbalanced-learn

      - name: Run preprocessing script
        run: python preprocessing/automate_Oka-Widhyartha.py

      - name: Upload processed datasets
        uses: actions/upload-artifact@v4
        with:
          name: processed-diabetes-dataset
          path: |
            preprocessing/diabetes_preprocessing/diabetes_train.csv
            preprocessing/diabetes_preprocessing/diabetes_test.csv
            preprocessing/label_encoded_values.csv
